JVickery-TBS:feature/validation support
qld-gov-au/ckanext-xloader pull request #113
Opened 2024-10-25 05:23 UTC by duttonw

testing final differences of what is in our version to what is going to upstream (prior to merging  https://github.com/ckan/ckanext-xloader/pull/200 )

2024-10-25 05:40 UTC, ThrawnCA requested changes

2024-10-25 05:40 UTC, ThrawnCA commented on ckanext/xloader/action.py
> +            log.exception('Unable to enqueued xloader res_id=%s', res_id)
"to enqueued" -> "to enqueue"

2024-10-25 05:40 UTC, ThrawnCA commented on ckanext/xloader/plugin.py
> +
Flake8 generally prefers single blank lines inside a class.

2025-09-19 03:49 UTC, duttonw commented
already merged via upstream

2025-09-19 03:49 UTC, closed without merging